import type {Metadata} from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "єЗбір",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ua">
      <body>{children}</body>
    </html>
  )
}
