import type {Metadata} from "next";
import "@/app/globals.css";
import Header from "@/components/Header";
import AuthHeader from "@/components/AuthHeader";
import AuthAside from "@/components/AuthAside";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Авторизація єЗбір",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ua">
      <body className='bg-[#E7EEF3]'>
      <AuthHeader/>
      <main className='flex h-[700px]'>
          {children}
          <AuthAside/>
      </main>
      <Footer/>
      </body>
      </html>
  );
}
